apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T13:27:23Z"
  name: order-canary
  resourceVersion: "661325"
  selfLink: /api/v1/namespaces/keptnorders-production/services/order
  uid: 215aaef4-1ce3-11ea-9ceb-42010a8e023f
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: order
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
