apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-10T14:52:27Z"
  name: frontend-canary
  resourceVersion: "32822"
  selfLink: /api/v1/namespaces/keptnorders-production/services/frontend
  uid: aeec4675-1b5c-11ea-b827-42010a8e0123
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
